export interface NavLeaf {
  label: string;
  route: string;
  icon?: string;
  soon?: boolean;
}

export interface NavBranch {
  label: string;
  icon: string;
  children: NavLeaf[];
}

export interface NavSection {
  label: string;
  items: (NavLeaf | NavBranch)[];
}

export function isNavBranch(item: NavLeaf | NavBranch): item is NavBranch {
  return 'children' in item && Array.isArray((item as NavBranch).children);
}

export const NAV_SECTIONS: NavSection[] = [
  {
    label: 'Foundations',
    items: [
      { icon: 'palette',        label: 'Colors',       route: '#/foundation/colors'        },
      { icon: 'align-left',     label: 'Typography',   route: '#/foundation/typography'    },
      { icon: 'ruler',          label: 'Spacing',      route: '#/foundation/spacing'       },
      { icon: 'square',         label: 'Borders',      route: '#/foundation/borders'       },
      { icon: 'layout-list',    label: 'Density',      route: '#/foundation/density'       },
      { icon: 'layers',         label: 'Shadows',      route: '#/foundation/shadows'       },
      { icon: 'sparkles',       label: 'Iconography',  route: '#/foundation/iconography'   },
      { icon: 'sparkles',       label: 'Motifs',       route: '#/foundation/motifs'        },
      { icon: 'brush',          label: 'Theming',      route: '#/foundation/theming'       },
      { icon: 'palette',        label: 'Color Harmony', route: '#/foundation/color-harmony' },
      { icon: 'play',           label: 'Motion',       route: '#/foundation/motion'        },
      { icon: 'shield',         label: 'Accessibility', route: '#/foundation/accessibility' },
      { icon: 'globe',          label: 'Internationalization', route: '#/foundation/internationalization' },
      { icon: 'message-circle', label: 'Voice & Tone', route: '#/foundation/voice-and-tone'},
    ],
  },
  {
    label: 'Core',
    items: [
      { icon: 'database', label: 'Data Source',  route: '#/core/data-source'  },
      { icon: 'layers',   label: 'Data Context', route: '#/core/data-context' },
      { icon: 'git-branch', label: 'Node Store', route: '#/core/data-context' },
    ],
  },
  {
    label: 'Data Display',
    items: [
      { icon: 'tag',                label: 'Badge',             route: '#/components/badge'          },
      { icon: 'keyboard',           label: 'Kbd',               route: '#/components/kbd'            },
      { icon: 'activity',           label: 'Progress Bar',      route: '#/components/progress-bar'   },
      { icon: 'loader',             label: 'Circular Progress', route: '#/components/circular-progress' },
      { icon: 'trending-up',        label: 'Stat Card',         route: '#/components/stat-card'      },
      { icon: 'user',               label: 'Avatar',            route: '#/components/avatar'         },
      { icon: 'users',              label: 'Avatar Group',      route: '#/components/avatar-group'   },
      { icon: 'loader',             label: 'Spinner',           route: '#/components/spinner'        },
      { icon: 'package',            label: 'Empty',             route: '#/components/empty'          },
      { icon: 'clock',              label: 'Timeline',          route: '#/components/timeline'       },
      { icon: 'git-commit',         label: 'Git Graph',         route: '#/components/git-graph'      },
      { icon: 'git-fork',           label: 'Treeview',          route: '#/components/tree'           },
      { icon: 'scan-line',          label: 'Barcode & QR Code', route: '#/components/barcode-qr'     },
      { icon: 'credit-card',        label: 'Credit Card',       route: '#/components/credit-card'    },
      { icon: 'table',              label: 'Datagridex',        route: '#/components/datagridex'     },
      { icon: 'calendar',           label: 'Scheduler',         route: '#/components/scheduler'      },
      { icon: 'bar-chart',          label: 'Gantt Chart',       route: '#/components/gantt'          },
      { icon: 'columns',            label: 'Kanban',            route: '#/components/kanban'         },
      { icon: 'terminal',           label: 'Terminal',          route: '#/components/terminal'       },
      { icon: 'star',               label: 'Rating',            route: '#/components/rating'         },
      { icon: 'columns', label: 'Carousel',          route: '#/components/carousel'       },
      { icon: 'maximize',           label: 'Lightbox',          route: '#/components/lightbox'       },
      { icon: 'columns',            label: 'Image Compare',     route: '#/components/image-compare'  },
      { icon: 'image',              label: 'Image Editor',      route: '#/components/image-editor'   },
      { icon: 'ratio',              label: 'Aspect Ratio',      route: '#/components/aspect-ratio'   },
      { icon: 'list',               label: 'List',              route: '#/components/list'           },
      { icon: 'table',              label: 'Table',              route: '#/components/table'          },
      { icon: 'panel-right',        label: 'Compose Bar',        route: '#/components/compose-bar'    },
      { icon: 'message-circle',     label: 'Comment Thread',     route: '#/components/comment-thread' },
      { icon: 'sliders-horizontal', label: 'Property Panel',     route: '#/components/property-panel' },
      { icon: 'file-text',          label: 'PDF Viewer',         route: '#/components/pdf-viewer'      },
      { icon: 'file-diff',          label: 'Text Diff',          route: '#/components/text-diff'       },
      { icon: 'credit-card',        label: 'Plan Cards',         route: '#/components/plan-cards'      },
      { icon: 'lock',               label: 'Feature Gate',       route: '#/components/feature-gate'    },
    ],
  },
  {
    label: 'Forms & Inputs',
    items: [
      { icon: 'square-check',      label: 'Checkbox',          route: '#/components/checkbox'           },
      { icon: 'circle-dot',        label: 'Radio Buttons',     route: '#/components/radio'              },
      { icon: 'toggle-left',       label: 'Switch',            route: '#/components/switch'             },
      { icon: 'text-cursor-input', label: 'Input',             route: '#/components/input'              },
      { icon: 'tag',               label: 'Field',             route: '#/components/field'              },
      { icon: 'layout-list',       label: 'Form Layout',       route: '#/components/form-layout'        },
      { icon: 'columns',           label: 'Input Group',       route: '#/components/input-group'        },
      { icon: 'chevron-down',      label: 'Select',            route: '#/components/select'             },
      { icon: 'search',            label: 'Combobox',          route: '#/components/combobox'           },
      { icon: 'layout-grid',       label: 'Grid Combobox',     route: '#/components/grid-combobox'      },
      { icon: 'palette',           label: 'Color Picker',       route: '#/components/color-picker'        },
      { icon: 'smile',             label: 'Emoji Picker',       route: '#/components/emoji-picker'        },
      { icon: 'search',            label: 'Lookups',            route: '#/components/lookups'             },
      { icon: 'layout-dashboard',  label: 'Form Builder',       route: '#/components/form-builder'        },
      { icon: 'menu',              label: 'Dropdown Menu',     route: '#/components/dropdown'           },
      { icon: 'align-left',        label: 'Textarea',          route: '#/components/textarea'           },
      { icon: 'at-sign',           label: 'Mention',           route: '#/components/mention'             },
      { icon: 'lock',              label: 'Password Input',    route: '#/components/password-input'     },
      { icon: 'shield',            label: 'Password Progress', route: '#/components/password-progress'  },
      { icon: 'hash',              label: 'OTP Input',         route: '#/components/otp-input'          },
      { icon: 'code',              label: 'Masked Input',      route: '#/components/masked-input'       },
      { icon: 'calendar',          label: 'Datepicker',        route: '#/components/datepicker'         },
      { icon: 'calendar-range',    label: 'Date Range Picker', route: '#/components/daterange-picker'   },
      { icon: 'calendar',          label: 'Calendar',          route: '#/components/calendar'           },
      { icon: 'calendar-range',    label: 'Range Calendar',    route: '#/components/range-calendar'     },
      { icon: 'clock',             label: 'Time Picker',       route: '#/components/time-picker'        },
      { icon: 'calendar-clock',    label: 'Datetime Picker',   route: '#/components/datetime-picker'    },
      { icon: 'sliders-horizontal',label: 'Slider & Range',    route: '#/components/slider-range'       },
      { icon: 'upload',            label: 'File Upload',       route: '#/components/file-upload'        },
      { icon: 'pen-tool',          label: 'Editor',            route: '#/components/editor'        },
      { icon: 'layout-list',       label: 'Block Editor',      route: '#/components/block-editor' },
      { icon: 'heading',           label: 'Markdown Editor',   route: '#/components/markdown-editor' },
      { icon: 'braces',            label: 'Code Editor',       route: '#/components/code-editor'        },
      { icon: 'square-split-horizontal',         label: 'Diff Editor',       route: '#/components/diff-editor'        },
      { icon: 'map-pin',           label: 'In-place Editor',   route: '#/components/inplace-editor'     },
      { icon: 'signature',          label: 'Signature Pad',     route: '#/components/signature-pad'      },
      { icon: 'filter',            label: 'Filter Expression', route: '#/components/filter-expression'  },
    ],
  },
  {
    label: 'Actions & Navigation',
    items: [
      { icon: 'zap',          label: 'Button',            route: '#/components/button'          },
      { icon: 'columns',      label: 'Button Group',      route: '#/components/button-group'    },
      { icon: 'columns',      label: 'Split Button',      route: '#/components/split-button'    },
      { icon: 'folder-dt',  label: 'Tabs',              route: '#/components/tabs'            },
      { icon: 'chevrons-right',label: 'Breadcrumbs',      route: '#/components/breadcrumbs'     },
      { icon: 'list',         label: 'Stepper',           route: '#/components/stepper'         },
      { icon: 'toggle-left',  label: 'Segmented Control', route: '#/components/segmented'       },
      { icon: 'plus',    label: 'FAB',               route: '#/components/fab'             },
      { icon: 'menu',         label: 'Navigation Menu',   route: '#/components/nav-menu'        },
      { icon: 'panel-top-dashed', label: 'Toolbar',           route: '#/components/toolbar'         },
      { icon: 'chevrons-right',label: 'Pager',            route: '#/components/pager'           },
    ],
  },
  {
    label: 'Layout & Overlays',
    items: [
      { icon: 'square',         label: 'Card',              route: '#/components/card'             },
      { icon: 'layout-panel-left', label: 'Panel',             route: '#/components/panel'            },
      { icon: 'layout-grid',    label: 'Grid',              route: '#/components/grid'             },
      { icon: 'layout-dashboard', label: 'Dock Manager',    route: '#/components/dock-manager'    },
      { icon: 'layout-grid',    label: 'Layout Manager',     route: '#/components/layout-manager'  },
      { icon: 'columns',        label: 'Masonry',             route: '#/components/masonry'         },
      { icon: 'grip-vertical',  label: 'Splitter',          route: '#/components/splitter'         },
      { icon: 'sidebar-left',   label: 'Sidebar',           route: '#/components/sidebar'          },
      { icon: 'building',       label: 'Company Switcher',  route: '#/components/company-switcher' },
      { icon: 'credit-card',    label: 'App Header',        route: '#/components/app-header'       },
      { icon: 'layout',         label: 'App Shell',         route: '#/components/app-shell'        },
      { icon: 'panel-right',    label: 'Drawer',            route: '#/components/drawer'           },
      { icon: 'maximize',       label: 'Modal',             route: '#/components/modal'            },
      { icon: 'minimize',       label: 'Window',            route: '#/components/window'           },
      { icon: 'chevron-down',   label: 'Accordion',         route: '#/components/accordion'        },
      { icon: 'alert-circle',   label: 'Alert',             route: '#/components/alert'            },
      { icon: 'alert-triangle', label: 'Message Bar',       route: '#/components/message-bar'      },
      { icon: 'message-square', label: 'Popover & Tooltip', route: '#/components/popover-tooltip'  },
      { icon: 'bell',           label: 'Toast',             route: '#/components/toast'            },
      { icon: 'message-circle', label: 'Snackbar',          route: '#/components/snackbar'         },
      { icon: 'bell',           label: 'Notification Center', route: '#/components/notification-center' },
      { icon: 'command',        label: 'Command Palette',   route: '#/components/command-palette'  },
      { icon: 'compass',        label: 'Coachmark',         route: '#/components/coachmark'        },
    ],
  },
  {
    label: 'Charts',
    items: [
      { icon: 'bar-chart-2',  label: 'Chart Kernel',       route: '#/charts/chart-kernel' },
      { icon: 'bar-chart',    label: 'Bar Chart',         route: '#/charts/bar-chart' },
      { icon: 'pie-chart',    label: 'Pie Chart',         route: '#/charts/pie-chart' },
      { icon: 'trending-up',  label: 'Line Chart',        route: '#/charts/line-chart' },
      { icon: 'activity',     label: 'Area Chart',        route: '#/charts/area-chart' },
      { icon: 'bar-chart',    label: 'Stacked Bar',       route: '#/charts/stacked-bar-chart' },
      { icon: 'layers',       label: 'Stacked Area',      route: '#/charts/stacked-area-chart' },
      { icon: 'circle-dot',   label: 'Bubble Chart',      route: '#/charts/bubble-chart' },
      { icon: 'gauge',        label: 'Gauge Chart',       route: '#/charts/gauge-chart' },
      { icon: 'chart-scatter',   label: 'Scatter Chart',     route: '#/charts/scatter-chart' },
      { icon: 'layout-grid',  label: 'Heatmap',           route: '#/charts/heatmap-chart' },
      { icon: 'bar-chart',    label: 'Grouped Bar',       route: '#/charts/grouped-bar-chart' },
      { icon: 'bar-chart-2',  label: 'Candlestick',       route: '#/charts/candlestick-chart' },
      { icon: 'layout-grid',  label: 'Treemap',           route: '#/charts/treemap-chart' },
      { icon: 'play',         label: 'Bar Race',          route: '#/charts/bar-race-chart' },
      { icon: 'activity',     label: 'Sparkline',         route: '#/charts/sparkline-chart' },
      { icon: 'filter',       label: 'Funnel',            route: '#/charts/funnel-chart' },
      { icon: 'bar-chart-2',  label: 'Histogram',         route: '#/charts/histogram-chart' },
      { icon: 'calendar',     label: 'Calendar Heatmap',  route: '#/charts/calendar-heatmap-chart' },
      { icon: 'bar-chart-2',  label: 'Combo Chart',       route: '#/charts/combo-chart' },
      { icon: 'hexagon',      label: 'Radar Chart',       route: '#/charts/radar-chart' },
      { icon: 'git-merge',    label: 'Sankey Chart',      route: '#/charts/sankey-chart' },
      { icon: 'sun',          label: 'Sunburst Chart',    route: '#/charts/sunburst-chart' },
      { icon: 'compass',      label: 'Polar Line Chart',  route: '#/charts/polar-line-chart' },
      { icon: 'bar-chart-2',  label: 'Waterfall Chart',   route: '#/charts/waterfall-chart' },
      { icon: 'users',        label: 'Org Chart',         route: '#/charts/org-chart' },
      { icon: 'bar-chart-2',  label: 'Cylinder Chart',    route: '#/charts/cylinder-chart' },
      { icon: 'git-branch',   label: 'Diagram Editor',    route: '#/charts/diagram-editor' },
      { icon: 'git-merge',    label: 'Fishbone Chart',    route: '#/charts/fishbone-chart' },
      { icon: 'share-2',      label: 'Graph Chart',       route: '#/charts/graph-chart' },
      { icon: 'map',          label: 'Map Chart',         route: '#/charts/map-chart' },
      { icon: 'activity',     label: 'Performance Graph', route: '#/charts/performance-graph' },
      { icon: 'filter',       label: 'Pyramid Chart',     route: '#/charts/pyramid-chart' },
      { icon: 'bar-chart-2',  label: 'Tiny Charts',       route: '#/charts/tiny-charts' },
      { icon: 'circle-dot',   label: 'Venn Chart',        route: '#/charts/venn-chart' },
      { icon: 'compass',      label: 'Wheel Diagram',     route: '#/charts/wheel-diagram' },
    ],
  },
  {
    label: 'Effects & Animations',
    items: [
      { icon: 'sparkles',       label: 'Sparkles', route: '#/effects/sparkles' },
      { icon: 'zap',            label: 'Confetti', route: '#/effects/confetti' },
      { icon: 'scan-line',      label: 'Shimmer',  route: '#/effects/shimmer'  },
      { icon: 'sparkles',       label: 'Rainbow',  route: '#/effects/rainbow'  },
      { icon: 'sun',            label: 'Shine',    route: '#/effects/shine'    },
      { icon: 'lightbulb',      label: 'Glow',     route: '#/effects/glow'     },
      { icon: 'move-horizontal',label: 'Marquee',  route: '#/effects/marquee'  },
      { icon: 'eye',            label: 'Fade',     route: '#/effects/fade'     },
    ],
  },
  {
    label: 'Utilities',
    items: [
      { icon: 'focus',        label: 'Focus Utilities', route: '#/utils/focus-utilities' },
      { icon: 'highlighter',  label: 'Highlight',       route: '#/utils/highlight'       },
      { icon: 'panel-right',  label: 'Scrollbar',       route: '#/utils/scrollbar'       },
      { icon: 'move',         label: 'Drag and Drop',   route: '#/utils/drag-drop'       },
      { icon: 'maximize',     label: 'Fullscreen',      route: '#/utils/fullscreen'      },
      { icon: 'chevron-up',   label: 'Hide on Scroll',  route: '#/utils/hide-on-scroll'  },
      { icon: 'more-vertical',label: 'Overflow',        route: '#/utils/overflow'        },
      { icon: 'app-window',   label: 'Code Preview',    route: '#/utils/code-preview'    },
    ],
  },
  {
    label: 'Blocks',
    items: [
      { icon: 'layout',          label: 'App Shell',         route: '#/blocks/app-shell'          },
      { icon: 'layout-dashboard',label: 'Dashboard',         route: '#/blocks/dashboard'          },
      { icon: 'lock',            label: 'Authentication',    route: '#/blocks/authentication'     },
      { icon: 'settings',        label: 'Settings',          route: '#/blocks/settings'           },
      { icon: 'list',            label: 'Feeds & Lists',     route: '#/blocks/feeds'              },
      { icon: 'clipboard-check', label: 'Project Workspace', route: '#/blocks/project-workspace' },
      { icon: 'help-circle',     label: 'Support Desk',      route: '#/blocks/support-desk'      },
      { icon: 'mail',            label: 'Email App',         route: '#/blocks/email'              },
    ],
  },
];
