// Generated by scripts/design-tokens.mjs.
penpot.ui.open('Spruce UI Foundations', '', { width: 360, height: 240 });
penpot.ui.onMessage(message => { if (message?.type === 'close') penpot.closePlugin(); });
